# Generated by Django 4.1.1 on 2022-10-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autores', models.TextField()),
                ('correo', models.EmailField(max_length=250)),
                ('division', models.CharField(max_length=250)),
                ('titulo', models.CharField(max_length=250)),
                ('tipo', models.CharField(choices=[('Platica', 'platica'), ('Poster', 'poster')], default='', max_length=250)),
                ('resumen', models.FileField(blank=True, null=True, upload_to='resumenes/%Y')),
            ],
        ),
    ]
