# Generated by Django 4.1.1 on 2022-10-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputmodel',
            name='resumen',
            field=models.FileField(null=True, upload_to='resumenes/%Y'),
        ),
    ]
