# Generated by Django 4.1.1 on 2022-11-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Aplicacion", "0002_alter_inputmodel_resumen"),
    ]

    operations = [
        migrations.AddField(
            model_name="inputmodel",
            name="estado",
            field=models.IntegerField(
                choices=[
                    (1, "sin revision"),
                    (2, "pendiente"),
                    (3, "aceptada"),
                    (4, "rechazada"),
                ],
                default=1,
            ),
        ),
    ]
