# Generated by Django 4.1.1 on 2022-11-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0004_alter_inputmodel_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputmodel',
            name='resumen',
            field=models.FileField(null=True, upload_to='resumenes/%Y/<django.db.models.fields.EmailField>'),
        ),
    ]
