# Generated by Django 4.1.1 on 2022-11-03 20:03

import Aplicacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0005_alter_inputmodel_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputmodel',
            name='resumen',
            field=models.FileField(null=True, upload_to=Aplicacion.models.update_filename),
        ),
    ]
