# Generated by Django 4.1.1 on 2022-11-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0008_inputmodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputmodel',
            name='tipo',
            field=models.CharField(choices=[('Platica', 'plática'), ('Poster', 'póster')], default='', max_length=250),
        ),
    ]
