# Generated by Django 4.1.1 on 2022-11-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0009_alter_inputmodel_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputmodel',
            name='tipo',
            field=models.CharField(choices=[('Platica', 'Plática'), ('Poster', 'Póster')], default='', max_length=250),
        ),
    ]
