# Generated by Django 4.1.1 on 2022-11-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0010_alter_inputmodel_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputmodel',
            name='numAutores',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1),
        ),
    ]
