# Generated by Django 4.1.1 on 2022-11-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0012_alter_inputmodel_numautores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputmodel',
            name='autores',
            field=models.TextField(default=''),
        ),
    ]
